# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 清华大学开源软件镜像站
brand: Tsinghua Open Source Mirrors
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:categories/:title/"
url: "https://mirrors.tuna.tsinghua.edu.cn"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false


sass:
    sass_dir: static/css

gems:
    - jekyll-babel
    - jekyll-sitemap

babel_js_extensions: 'es6'

exclude: [Gemfile, Gemfile.lock, README.md, gen_robot.sh, vendor]

# Content Related
new_mirrors: [arch4edu, ros, elvish, HHVM, steamos, bjlx, loongson, tensorflow, elasticstack]

descriptions:
  AOSP: 'Android 操作系统源代码'
  AUR: 'Arch Linux 用户软件库'
  CRAN: 'R 语言的可执行文件、源代码和说明文件，也收录了各种用户撰写的软件包'
  CTAN: 'TeX 的各种发行版、软件包和文档'
  CocoaPods: 'Objective-C 和 Swift 的依赖管理器'
  ELK: '现已更名为 Elastic Stack，仅保留用作向后兼容'
  HHVM: 'Facebook 开发的高性能 PHP 语言虚拟机'
  NetBSD: 'NetBSD 的安装镜像和官方软件包仓库'
  OpenBSD: 'OpenBSD 的安装镜像和官方软件包仓库'
  alpine: 'Alpine Linux 的安装镜像和官方软件包仓库'
  anaconda: '用于科学计算的 Python 发行版'
  antergos: '基于 Arch Linux 的使用 GNOME 3 的发行版，曾用名 Cinnarch'
  anthon: 'Anthon Linux (安同 Linux)的安装镜像和官方软件包仓库'
  apache: 'Apache 基金会赞助的各个项目'
  arch4edu: '用于 Arch Linux 的一系列科研、教学所需工具'
  archlinux: 'Arch Linux 的安装镜像和官方软件包仓库'
  archlinuxarm: '用于 arm 平台的 Arch Linux 镜像和软件包仓库'
  archlinuxcn: '由 Arch Linux 中文社区驱动的非官方用户仓库,包含中文用户常用软件、工具、字体/美化包等'
  Bananian: '为 Banana Pi 制作的，基于官方 Debian 仓库的发行版镜像和软件包仓库'
  bjlx: '北京龙芯 & Debian 俱乐部 的公开软件源'
  blackarch: '用于安全评估的基于 Arch Linux 的轻量级发行版'
  centos: 'CentOS 的安装镜像和官方软件包仓库'
  ceph: '高性能对象存储和文件系统'
  chakra: '专注于 Qt 与 KDE 软件的 Linux 发行版'
  ctex: '旧版 CTEX 安装镜像存档'
  cygwin: 'Cygwin 官方软件包仓库'
  debian: 'Debian Linux 的官方软件包仓库'
  debian-cd: 'Debian Linux 的安装镜像'
  deepin: 'Deepin Linux 的官方软件包仓库'
  deepin-cd: 'Deeping Linux 的安装镜像'
  dell: 'Dell 服务器管理工具'
  docker: 'Docker 的官方软件包仓库'
  dotdeb: '用于 Debian 服务器的额外镜像源'
  elasticstack: 'ELK 系列数据分析工具，5.x 之后改名为 Elastic Stack'
  elpa: 'Emacs 内建包管理器 package.el 的软件源'
  elrepo: 'RHEL 及其变体的 RPM 软件包仓库'
  elvish: 'TUNA 前会长 xiaq 开发的革命性 Shell'
  epel: '企业版 Linux 附加软件包'
  fedora: 'Fedora Linux 的安装镜像和官方软件包仓库'
  gentoo: 'Gentoo Linux 的 Stage 3 镜像'
  gentoo-portage: 'Gentoo Linux 的 Portage 包管理器镜像源'
  gitlab-ce: 'Gitlab 社区版'
  gitlab-ci-multi-runner: 'GitLab 持续集成框架'
  gnu: 'GNU 项目的软件包源码'
  grafana: '开源的数据可视化工具'
  hackage: 'Haskell 社区的中心软件包仓库'
  Homebrew: ' Homebrew 的 formula 索引的镜像，二进制预编译包的镜像请见 homebrew-bottles'
  homebrew-bottles: '预编译的 Homebrew 软件包'
  infinality-bundle: 'Arch Linux 的字体渲染软件包'
  influxdata: '时间序列数据平台'
  ius: '为企业版 LInux 提供最新软件包的镜像源'
  jenkins: '用 Java 编写的持续集成框架'
  kali: 'Kali Linux 的官方软件包仓库'
  kali-images: 'Kali Linux 的安装镜像'
  kernel: '各个版本的Linux 内核源代码'
  kodi: '开源的多媒体播放器，原名 XBMC'
  linux.git: 'Linux 内核源代码的 Git 仓库'
  linuxmint: 'Linux Mint 的官方软件源'
  linuxmint-cd: 'Linux Mint 的安装镜像'
  loongson: '用于龙芯电脑的软件包'
  lxc-images: 'Linux 容器的镜像'
  mageia: 'Mageia Linux （衍生于Mandriva Linux）的安装镜像和官方软件包仓库'
  manjaro: 'Manjaro Linux 的官方软件源'
  manjaro-cd: 'Manjanro Linux 的安装镜像'
  mariadb: '衍生于 MySQL 的开源关系数据库'
  mongodb: '开源的跨平台 NoSQL 文档型数据库'
  msys2: '用于编译原生 Windows 程序的类 Linux 开发环境'
  mysql: 'MySQL 安装包及各种工具下载'